export const OCCURRENCE_STATUSES = {
  SCHEDULED: "scheduled",
  QUEUED: "queued",
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  NEEDS_RETRY: "needs_retry",
  CANCELLED: "cancelled",
} as const;

export type OccurrenceStatus = (typeof OCCURRENCE_STATUSES)[keyof typeof OCCURRENCE_STATUSES];

export const RETRYABLE_STATUSES = [
  OCCURRENCE_STATUSES.NEEDS_RETRY,
  OCCURRENCE_STATUSES.FAILED,
  OCCURRENCE_STATUSES.RUNNING,
  OCCURRENCE_STATUSES.QUEUED,
  OCCURRENCE_STATUSES.SCHEDULED,
] as const;

export const FORCE_RETRYABLE_STATUSES = [
  ...RETRYABLE_STATUSES,
  OCCURRENCE_STATUSES.SUCCEEDED,
  OCCURRENCE_STATUSES.CANCELLED,
] as const;

export const RETRY_REASON_CODES = {
  MANUAL_RETRY: "MANUAL_RETRY",
  LOCK_CONTENTION: "LOCK_CONTENTION",
  PROVIDER_REJECTED: "PROVIDER_REJECTED",
  WINDOW_MISSED: "WINDOW_MISSED",
  WORKER_STALLED: "WORKER_STALLED",
  RETRY_EXHAUSTED: "RETRY_EXHAUSTED",
} as const;

export type RetryReasonCode = (typeof RETRY_REASON_CODES)[keyof typeof RETRY_REASON_CODES];
