#!/usr/bin/env bash
# ============================================================
# OpenClaw Mission Control — Bootstrap Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/kenandevx/mission-control/main/scripts/install.sh | bash
#
# Default install location: ~/.openclaw/workspace/mission-control
# (inside the OpenClaw workspace — matches openclaw setup layout)
# Override with: INSTALL_DIR=/path/to/dir bash -c "$(curl ...)"
# ============================================================
set -euo pipefail

# ── Constants ───────────────────────────────────────────────
GIT_REPO="git@github.com:kenandevx/mission-control.git"
GIT_BRANCH="${GIT_BRANCH:-main}"
DEFAULT_DIR="$HOME/.openclaw/workspace/mission-control"
RUN_AS="${RUN_AS:-$(whoami)}"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[install]${NC} $1"; }
warn()  { echo -e "${YELLOW}[install]${NC} $1"; }
err()   { echo -e "${RED}[install]${NC} $1" >&2; }
step()  { echo -e "${CYAN}[install]${NC} $1"; }

# ── Header ──────────────────────────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════════════════╗"
echo "║    OpenClaw Mission Control — Bootstrap Installer     ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# ── Resolve install directory ────────────────────────────────
if [ -n "${INSTALL_DIR:-}" ]; then
  :
elif [ -d "$HOME/.openclaw/workspace/mission-control/.git" ]; then
  INSTALL_DIR="$HOME/.openclaw/workspace/mission-control"
elif [ -d "$(dirname "$DEFAULT_DIR")/.git" ]; then
  INSTALL_DIR="$(dirname "$DEFAULT_DIR")"
else
  INSTALL_DIR="$DEFAULT_DIR"
fi

info "Installing to: $INSTALL_DIR"
echo ""

# ── Prerequisites ───────────────────────────────────────────
step "Checking prerequisites ..."
for cmd in docker git node npm openssl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    err "Missing required command: $cmd"
    exit 1
  fi
done

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0")
if [ "$(printf '%s\n' "20.10.0" "$DOCKER_VERSION" | sort -V | head -n1)" != "20.10.0" ]; then
  err "Docker 20.10+ required. Found: $DOCKER_VERSION"
  exit 1
fi
info "Docker $DOCKER_VERSION — OK"

# Check for Redis (required for BullMQ)
if ! command -v redis-server >/dev/null 2>&1 && ! command -v redis-cli >/dev/null 2>&1; then
  warn "Redis not found. BullMQ requires Redis."
  warn "Install: sudo apt install redis-server"
fi

step "Checking SSH access to GitHub ..."
if ssh -T git@github.com 2>/dev/null || true | grep -q "successfully"; then
  info "SSH access to GitHub — OK"
else
  warn "No SSH access to GitHub. Switching to HTTPS clone."
  GIT_REPO="https://github.com/kenandevx/mission-control.git"
fi
echo ""

# ── Clone or update ────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Existing install found at $INSTALL_DIR"
  step "Pulling latest changes ..."
  cd "$INSTALL_DIR"
  git pull origin "$GIT_BRANCH" 2>&1 | tail -3 || true
else
  step "Cloning mission-control into $INSTALL_DIR ..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --branch "$GIT_BRANCH" "$GIT_REPO" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ── Environment setup ──────────────────────────────────────
if [ ! -f .env ]; then
  step "Creating .env from template ..."
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  API_USER="admin"
  API_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  cat > .env << EOF
# Mission Control — generated by install.sh on $(date -u +%Y-%m-%d)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
API_USER=${API_USER}
API_PASS=${API_PASS}
DATABASE_URL=postgresql://openclaw:${POSTGRES_PASSWORD}@localhost:5432/mission_control
OPENCLAW_DATABASE_URL=postgresql://openclaw:${POSTGRES_PASSWORD}@localhost:5432/mission_control
OPENCLAW_GATEWAY_URL=ws://127.0.0.1:18789
OPENCLAW_GATEWAY_TOKEN=
EOF
  chmod 600 .env
  warn ".env created — credentials:"
  echo "  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "  API_USER=${API_USER}"
  echo "  API_PASS=${API_PASS}"
  echo ""
  warn "Save these credentials — they cannot be recovered."
  echo ""
else
  info ".env already present — skipping"
fi

cp .env .env.local 2>/dev/null || true

# ── Runtime directories ───────────────────────────────────────
mkdir -p .runtime/bridge-logger .runtime/pids .runtime/logs
touch .runtime/bridge-logger/bridge-logger.lock .runtime/bridge-logger/offsets.json
chmod 666 .runtime/bridge-logger/bridge-logger.lock .runtime/bridge-logger/offsets.json

# ── Docker: start database only ───────────────────────────
step "Starting database container ..."
docker compose up -d db
docker compose up -d db-init

step "Waiting for database to be ready ..."
until docker compose exec -T db pg_isready -U openclaw -d mission_control >/dev/null 2>&1; do
  printf "."
  sleep 1
done
echo ""
info "Database ready."

step "Waiting for schema initialization ..."
while docker compose ps db-init 2>/dev/null | grep -q "Up"; do
  printf "."
  sleep 1
done
echo ""
info "Schema initialized."

# ── npm install + build ──────────────────────────────────────
step "Installing npm dependencies ..."
npm install 2>&1 | tail -3

step "Building production Next.js ..."
npm run build 2>&1 | tail -5

# ── mc-services: start host-level daemons ────────────────────
step "Starting all services (task-worker, gateway-sync, bridge-logger, Next.js) ..."
bash scripts/mc-services.sh start 2>&1 | sed 's/^/  /'

# ── Convenience symlinks ─────────────────────────────────────
step "Creating convenience symlinks in /usr/local/bin ..."
for script in install clean update uninstall mc-services dev; do
  symlink="/usr/local/bin/mc-${script}"
  source_file="$INSTALL_DIR/scripts/${script}.sh"
  if [ -f "$source_file" ]; then
    ln -sf "$source_file" "$symlink"
    chmod +x "$source_file"
    info "  /usr/local/bin/mc-${script}"
  fi
done
echo ""

# ── Done ────────────────────────────────────────────────────
echo "╔═══════════════════════════════════════════════════════╗"
echo "║            Installation complete!                   ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""
echo "Location: $INSTALL_DIR"
echo ""
echo "Services running (production):"
echo "  PostgreSQL (Docker)   — port 5432"
echo "  task-worker (host)    — executes agent tickets"
echo "  gateway-sync (host)   — imports openclaw sessions"
echo "  bridge-logger (host)  — tails openclaw logs to DB"
echo "  Next.js (host)        — production build, port 3000"
echo ""
echo "Commands:"
echo "  mc-services stop      — stop all services"
echo "  mc-services status    — check status"
echo "  mc-update            — pull latest + rebuild + restart"
echo "  mc-clean             — fresh start (destroys DB)"
echo "  bash dev.sh           — start dev mode (hot-reload, foreground)"
echo ""
echo "Open: http://localhost:3000"
echo ""
