#!/usr/bin/env bash
set -euo pipefail

# Mission Control — One-time installer
# Clones the repo, configures environment, starts all services.
# Safe to re-run on an existing install (will skip clone and pull latest).

GIT_URL="git@github.com:claw-arsenal/mission-control.git"
DEFAULT_DIR="$HOME/mission-control"
GIT_BRANCH="${GIT_BRANCH:-main}"
# Allow overriding via env or detect current directory if already in a git repo
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# If already inside the mission-control repo, use that path
if [ -d "$PROJECT_ROOT/.git" ] && git -C "$PROJECT_ROOT" remote get-url origin 2>/dev/null | grep -q "mission-control"; then
  INSTALL_DIR="$PROJECT_ROOT"
else
  INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"
fi

set -e

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[install]${NC} $1"; }
warn()  { echo -e "${YELLOW}[install]${NC} $1"; }
err()   { echo -e "${RED}[install]${NC} $1" >&2; }

# ── Header ─────────────────────────────────────────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════╗"
echo "║     Mission Control — One-time Setup     ║"
echo "╚═══════════════════════════════════════════╝"
echo ""

# ── Detect existing install ─────────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Repository found at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  warn "Pulling latest changes..."
  git pull origin "$GIT_BRANCH" 2>/dev/null || true
else
  info "Cloning mission-control into $INSTALL_DIR ..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --branch "$GIT_BRANCH" "$GIT_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ── Prerequisites ────────────────────────────────────────────────────────────
info "Checking prerequisites ..."
for cmd in docker docker-compose git node npm; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    err "Missing required command: $cmd"
    exit 1
  fi
done

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0")
if [ "$(printf '%s\n' "20.10.0" "$DOCKER_VERSION" | sort -V | head -n1)" != "20.10.0" ]; then
  err "Docker 20.10+ required. Found: $DOCKER_VERSION"
  exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//')
if [ "$(printf '%s\n' "24.0.0" "$NODE_VERSION" | sort -V | head -n1)" != "24.0.0" ]; then
  warn "Node.js 24+ recommended. Found: $NODE_VERSION"
fi

info "All prerequisites OK"

# ── Environment ─────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  info "Creating .env from template ..."
  # Generate strong random passwords
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  API_USER="admin"
  API_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  cat > .env << EOF
# Mission Control — generated by install.sh on $(date -u +%Y-%m-%d)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
API_USER=${API_USER}
API_PASS=${API_PASS}
OPENCLAW_GATEWAY_URL=ws://127.0.0.1:18789
OPENCLAW_GATEWAY_TOKEN=
EOF
  chmod 600 .env
  warn ".env created with generated passwords:"
  echo "  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "  API_USER=${API_USER}"
  echo "  API_PASS=${API_PASS}"
  echo ""
  warn "Save these credentials — the password cannot be recovered."
  echo ""
else
  info ".env already present"
fi

# Copy for Next.js dev server
cp .env .env.local 2>/dev/null || true

# ── Pre-create runtime dir (for bridge-logger lock file) ──────────────────
info "Creating runtime directory ..."
mkdir -p .runtime/bridge-logger
touch .runtime/bridge-logger/bridge-logger.lock
chmod 666 .runtime/bridge-logger/bridge-logger.lock

# ── Docker images ───────────────────────────────────────────────────────────
info "Pulling base Docker images ..."
docker compose pull db postgres 2>&1 | grep -v "^Pulling\|^$\|" | head -5 || true

info "Building custom images ..."
docker compose build --pull bridge-logger task-worker gateway-sync 2>&1 | tail -3

# ── Start services ──────────────────────────────────────────────────────────
info "Starting database ..."
docker compose up -d db
docker compose up -d db-init

info "Waiting for database to be ready ..."
until docker compose exec -T db pg_isready -U openclaw -d mission_control >/dev/null 2>&1; do
  printf "."
  sleep 1
done
echo ""
info "Database ready."

info "Waiting for schema initialization ..."
while docker compose ps db-init 2>/dev/null | grep -q "Up"; do
  printf "."
  sleep 1
done
echo ""
info "Schema initialized."

info "Starting supporting services ..."
docker compose up -d gateway-sync bridge-logger task-worker

# ── npm install ─────────────────────────────────────────────────────────────
info "Installing npm dependencies ..."
npm install

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════╗"
echo "║            Installation complete!         ║"
echo "╚═══════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo ""
echo "  1. Start Docker services (keep running in a terminal):"
echo "     npm run dev:docker"
echo ""
echo "  2. Start the dev server (in another terminal):"
echo "     npm run dev"
echo ""
echo "  Or run both together:"
echo "     npm run dev:full"
echo ""
echo "  Open: http://localhost:3000"
echo ""
echo "  Credentials saved in: $INSTALL_DIR/.env"
echo ""
